version: '3'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8090:8090"
